# ============================================================
# Cerberix Network — Internal Server DNS
# ============================================================

# Web server
address=/heros.quantumbytz.com/192.168.1.10

# Mail server
address=/post.quantumbytz.com/192.168.1.20
address=/mail.quantumbytz.com/192.168.1.20

# MX record for mail delivery
mx-host=quantumbytz.com,post.quantumbytz.com,10
