#
# LightDM GTK+ Greeter — Cerberix defaults
# Separate from lightdm.conf. Controls only the greeter's own appearance.
#
[greeter]
background = /usr/share/backgrounds/cerberix/cerberix-desktop-background-moon.png
theme-name = Adwaita-dark
icon-theme-name = Papirus-Dark
font-name = Inter 11
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %a %b %e %l:%M %p
position = 50%,center 50%,center
